Fix cli commands error (#915)
Upgrade Typer lib to 0.19.2 to resolve this issue:

TypeError: Parameter.make_metavar() missing 1 required positional argument: 'ctx'